spotify:
  client:
    id: #{SPOTIFY_CLIENT_ID}
    secret: #{SPOTIFY_CLIENT_SECRET}
  uri:
    authorize: https://accounts.spotify.com/authorize?response_type=code&client_id={client_id}&scope={scope}&redirect_uri={redirect_uri}&state={state}
    auth: https://accounts.spotify.com/api
    api: https://api.spotify.com/v1
  redirect:
    uri: http://localhost:8080/auth/login/spotifyCallback
  scope: user-read-private user-read-email playlist-read-private playlist-read-collaborative playlist-modify-public playlist-modify-private

tidal:
  uri:
    api: https://api.tidal.com/v1/
  token: #{TIDAL_API_TOKEN}

#db
spring:
  datasource:
    url: jdbc:h2:mem:musicmaster
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop