apiVersion: v1
kind: ConfigMap
metadata:
  name: musicmaster-configmap
data:
  ELASTIC_APM_SERVER_URL: http://apm-server:8200
  ELASTIC_APM_SERVICE_NAME: musicmaster-api
  ELASTIC_APM_APPPLICATION_PACKAGES: com.musicmaster.main
  JAVA_TOOLS_OPTIONS: -javaagent:/apm-agent/elastic-apm-agent.jar