apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicmaster-deploy
  labels:
   app: musicmaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musicmaster
  template:
    metadata:
      labels:
        app: musicmaster
    spec:
      containers:
      - name: musicmaster-api
        image: musicmaster-api
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: musicmaster-secret
        - configMapRef:
            name: musicmaster-configmap
        volumeMounts:
        - mountPath: /apm-agent
          name: apm-volume
      initContainers:
        - name: apm-agent
          image: docker.elastic.co/observability/apm-agent-java:1.19.0
          volumeMounts:
          - mountPath: /apm-agent
            name: apm-volume
          command: ['cp', '-v', '/usr/agent/elastic-apm-agent.jar', '/apm-agent']
      volumes:
      - name: apm-volume
        emptyDir: {}
