kind: Secret
apiVersion: v1
metadata:
  name: musicmaster-secret
type: Opaque
stringData:
  SPOTIFY_CLIENT_ID: #{CLIENT_ID}
  SPOTIFY_CLIENT_SECRET: #{CLIENT_SECRET}
  TIDAL_TOKEN: #{TIDAL_TOKEN}
  SPRING_DATASOURCE_URL: jdbc:h2:mem:musicmaster
  ELASTIC_APM_SECRET_TOKEN: #{ELASTIC_APM_SECRET}

